---
# tasks file for setting up K8s Certificate Manager

- name: Add Kubernetes jetstack repo
  community.kubernetes.helm_repository:
    name: jetstack
    repo_url: "https://charts.jetstack.io"

- name: Deploy latest version of cert-manager
  community.kubernetes.helm:
    name: cert-manager
    chart_ref: jetstack/cert-manager
    namespace: cert-manager
    create_namespace: yes
    values:
      installCRDs: true

- name: Create letsencrypt ACME Issuer manifest
  template:
    src: letsencrypt-issuer.yml.j2
    dest: /opt/letsencrypt-issuer.yml
    mode: 0644

- name: Apply Issuer manifest to the cluster
  community.kubernetes.k8s:
    src: /opt/letsencrypt-issuer.yml
    state: present
