= Hobbyist Kubernetes on bare-metal

So while we're in this quarantine with nothing better to do I decided
that I wanted to set up my own Kubernetes cluster. Partly because I
really wanted to learn how to do that and partly because managed cloud
Kubernetes instances are _expensive_! (And I work for RedHat, so at
least I have plenty of access, but they are all limited in a number of
ways)

So I first did all the work manually, which I turned into a guide with
links to all the places where I found the necessary information. You can
read it here:

xref:manual.adoc[Manual Installation Guide]

But when you don't know what you're doing and you're experimenting a lot
you also tend to break things a lot. And sometimes in ways where you have
no idea how to get back to a known-to-work state. So that's when I decided
it was time to learn https://www.ansible.com/resources/get-started[Ansible]
and automate the creation of my cluster. If you want to know how to do that
continue to:

xref:ansible/README.adoc[Automatic Installation Guide]
