---
# tasks file setting up etcd
- name: Unpack etcd
  unarchive:
    src: https://storage.googleapis.com/etcd/v{{ etcd_version }}/etcd-v{{ etcd_version }}-linux-amd64.tar.gz
    remote_src: yes
    dest: /opt/etcd
    mode: 0755
  notify: restart_etcd

- name: Configuring etcd
  template:
    src: etcd.service.j2
    dest: /etc/systemd/system/etcd.service
    owner: root
    group: root
    mode: 0644
  notify: restart_etcd

- name: make sure we reboot if any of the previous steps was applied
  meta: flush_handlers
