---
# tasks file setting up Wireguard
- name: Install Wireguard
  apt:
    name: wireguard
    state: present

- name: Check setup
  shell: wg show wg0 dump
  register: wireguard_check
  ignore_errors: true
  changed_when: false

- name: Setup wireguard
  include_tasks: setup.yml
  when: wireguard_check is failed or ( wireguard_check.stdout_lines|length != play_hosts|length )

- name: Update hosts file with short names and internal IPs of all nodes
  lineinfile:
    dest: /etc/hosts
    regexp: '{{ hostvars[item].internal_ip }}.*{{ hostvars[item].shortname }}$'
    line: "{{ hostvars[item].internal_ip }} {{ hostvars[item].shortname }}"
    state: present
  with_items: "{{ play_hosts }}"

- name: UFW - Allow incoming Wireguard traffic
  community.general.ufw:
    rule: allow
    interface: eth0
    direction: in
    to_port: '51820'
    state: enabled
  notify:
  - restart_ufw

- name: UFW - Allow all incoming traffic on Wireguard interface
  community.general.ufw:
    rule: allow
    interface: wg0
    direction: in
    state: enabled
  notify:
  - restart_ufw

- name: make sure we reboot if any of the previous steps was applied
  meta: flush_handlers
