---
# tasks file setting up Wireguard
- name: Generate private key
  shell: wg genkey
  register: wireguard_genkey
  changed_when: false

- name: Set the private key as a host fact
  set_fact:
    private_key: "{{ wireguard_genkey.stdout }}"

- name: Generate public key
  shell: "echo {{ private_key }} | wg pubkey"
  register: wireguard_pubkey
  changed_when: false

- name: Set the public key as a host fact
  set_fact:
    public_key: "{{ wireguard_pubkey.stdout }}"

- name: Create wireguard directory
  file:
    path: /etc/wireguard
    state: directory
    mode: 0700

- name: Configuring wireguard
  template:
    src: wg.conf.j2
    dest: /etc/wireguard/wg0.conf
    owner: root
    group: root
    mode: 0600
  notify: restart_wireguard
