---
# This playbook creates a Kubernetes cluster

- name: Set up K8s cluster
  hosts: nodes
  remote_user: root
  any_errors_fatal: true

  roles:
  - lowlevel_setup
  - wireguard
  - etcd
  - kubeadm

  handlers:
  - include: common-handlers.yml
  
- name: Install apps on K8s cluster
  hosts: master
  remote_user: root
  any_errors_fatal: true

  roles:
  - helm
  - dashboard
  - metrics
  - ingress
  - cert_manager
