---
# tasks file setting up K8s using Kubeadm
- name: Add Google Cloud key
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present

- name: Configure Kubernetes repository
  apt_repository:
    repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
    state: present

- name: Install Kube tools
  apt:
    name: [ 'kubeadm', 'kubectl', 'kubelet' ]
    state: present

- name: Create Kubelet configuration
  template:
    src: kubelet.j2
    dest: /etc/default/kubelet
    owner: root
    group: root
    mode: 0644

- name: Setup K8s master node
  include_tasks: master.yml
  when: inventory_hostname == groups['nodes'][0]

- name: Setup K8s slave nodes
  include_tasks: slave.yml
  when: inventory_hostname != groups['nodes'][0]

- name: Setup overlay network
  include_tasks: weave.yml

- name: make sure we reboot if any of the previous steps was applied
  meta: flush_handlers
